Malendar\Domain\Model\Master\Master:
  type: entity
  repositoryClass: Malendar\Infrastructure\Persistence\DoctrineMasterRepository
  table: master
  embedded:
    id:
      class: Malendar\Domain\Model\ValueObject\UuId
      columnPrefix: false
  fields:
    name:
      type: string
      length: 255
    acronym:
      type: string
      length: 255
    description:
      type: text
    created_at:
      type: datetime
  manyToMany:
    users:
      targetEntity: Malendar\Domain\Model\User\User
      mappedBy: masters
  oneToMany:
    courses:
      targetEntity: Malendar\Domain\Model\Course\Course
      mappedBy: master