Malendar\Domain\Model\Calendar\Calendar:
  type: entity
  table: calendar
  embedded:
    id:
      class: Malendar\Domain\Model\ValueObject\UuId
      columnPrefix: false
  oneToOne:
      course:
        targetEntity: Malendar\Domain\Model\Course\Course
        inversedBy: calendar
        joinColumn:
          name: course_id
          referencedColumnName: id
