Malendar\Domain\Entities\Calendar\Calendar:
  type: entity
  table: calendar
  embedded:
    id:
      class: Malendar\Domain\Entities\ValueObject\UuId
      columnPrefix: false
  oneToOne:
      course:
        targetEntity: Malendar\Domain\Entities\Course\Course
        inversedBy: calendar
        joinColumn:
          name: course_id
          referencedColumnName: id
