Malendar\Domain\Model\User\User:
  type: entity
  repositoryClass: Malendar\Infrastructure\Persistence\DoctrineUserRepository
  table: user
  embedded:
    id:
      class: Malendar\Domain\Model\ValueObject\UuId
      columnPrefix: false
    email:
      class: Malendar\Domain\Model\ValueObject\Email
      columnPrefix: false
  fields:
    name:
      type: string
      length: 255
    hashCode:
      type: string
    admin:
      type: boolean
  manyToMany:
    masters:
      targetEntity: Malendar\Domain\Model\Master\Master
      joinTable:
        name: users_masters
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          master_id:
            referencedColumnName: id