Malendar\Domain\Model\Course\Course:
  type: entity
  table: course
  embedded:
    id:
      class: Malendar\Domain\Model\ValueObject\UuId
      columnPrefix: false
  fields:
    date_start:
      type: datetime
    date_end:
      type: datetime
    class_days:
      type: simple_array
  manyToOne:
    master:
      targetEntity: Malendar\Domain\Model\Master\Master
      inversedBy: courses
      joinColumn:
        name: master_id
        referencedColumnName: id
  oneToOne:
    calendar:
      targetEntity: Malendar\Domain\Model\Calendar\Calendar
      mappedBy: course
