Malendar\Domain\Entities\Master\Master:
  type: entity
  table: master
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
    acronym:
      type: string
      length: 255
    description:
      type: text
  manyToOne:
    user:
      targetEntity: Malendar\Domain\Entities\User\User
      inversedBy: masters
      joinColumn:
        name: user_id
        referencedColumnName: uuid
  oneToMany:
    courses:
      targetEntity: Malendar\Domain\Entities\Course\Course
      mappedBy: master