Malendar\Domain\Entities\User\User:
  type: entity
  table: user
  embedded:
    uuid:
      class: Malendar\Domain\Entities\ValueObject\UserId
      columnPrefix: false
    email:
      class: Malendar\Domain\Entities\ValueObject\Email
      columnPrefix: false
  fields:
    name:
      type: string
      length: 255
    hashCode:
      type: string